### ISSUE TITLE
This code has a serious problem.

### ISSUE THREAD

**Issue by ryuhojin** [teknologi-umum/flourite#72]
const Markdown = [
    // headings
    { pattern: /^(#){2,6}\s.+/, type: 'keyword' },
```
    **// headings alternate syntax
    { pattern: /^(?!!)(=|-){2,}(?<!>)$/, type: 'meta.module' },**
```
    // images
    { pattern: /(!)?\[.+\]\(.+\)/, type: 'keyword' },
    // links 2
    { pattern: /\[.+\]\[.+\]/, type: 'keyword' },
    // links 3
    { pattern: /^\[.+\]:\s?(<)?(http)?/, type: 'keyword' },
    // blockquotes
    { pattern: /^(> .*)+/, type: 'macro' },
    // code block
    { pattern: /^```([A-Za-z0-9#_]+)?$/, type: 'keyword' },
    // frontmatter
    { pattern: /^---$/, type: 'meta.module', nearTop: true },
];

"?<!" negative lookbehind regular expression not supported Safari and FireFox
How Can I fix it?

**Comment by taomanwai** [comment]
Any update on this issue? Is it fixed in the latest version of flourite?

**Comment by aldy505** [comment]
> Any update on this issue? Is it fixed in the latest version of flourite?

Hi! As far as I know, it's not yet fixed. PRs are welcome though.

**Comment by Niek** [comment]
I have opened a PR to fix this: #75 
Hope you're able to merge and release this, @aldy505.
